backend:
  name: github
  repo: Viguro79/pmequitherapie
  branch: gh-pages
  base_url: https://sveltia-cms-auth.vincent-guerinrousteau.workers.dev

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "À propos"
        name: "apropos"
        file: "apropos.md"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Classe principale", name: "mainClass", widget: "string", required: false }
          - { label: "Contenu", name: "body", widget: "markdown" }
      - label: "Accueil"
        name: "home"
        file: "index.md"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Contenu", name: "body", widget: "markdown" }
      - label: "Équithérapie"
        name: "equitherapie"
        file: "equitherapie.md"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Classe principale", name: "mainClass", widget: "string", required: false }
          - { label: "Contenu", name: "body", widget: "markdown" }
      - label: "Informations pratiques"
        name: "infos"
        file: "infos.md"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Classe principale", name: "mainClass", widget: "string", required: false }
          - { label: "Contenu", name: "body", widget: "markdown" }
      - label: "Liens utiles"
        name: "liens"
        file: "liens.md"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Classe principale", name: "mainClass", widget: "string", required: false }
          - { label: "Contenu", name: "body", widget: "markdown" }