backend:
  name: github
  repo: Viguro79/pmequitherapie_staging
  branch: gh-pages
  app_id: Ov23li7NLt4kObYbdnOt 

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "À propos"
        name: "apropos"
        file: "apropos.md"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Classe principale", name: "mainClass", widget: "string", required: false }
          - { label: "Contenu", name: "body", widget: "markdown" }
      - label: "Accueil"
        name: "home"
        file: "index.md"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Contenu", name: "body", widget: "markdown" }